// app/layout.js (or layout.tsx)
import { Montserrat, Space_Grotesk } from "next/font/google";
import "./globals.css";

// Load Montserrat
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Choose weights as needed
  display: "swap",
});

// Load Space Grotesk
const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk", // ✅ must match your CSS var name
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "BAD RETENTION",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${spaceGrotesk.variable} antialiased scroll-smooth bg-white text-gray-900`}
      >
        <main className="min-h-screen">{children}</main>
      </body>
    </html>
  );
}
